version: '3'

services:
  front:
    #env_file:
    # - ./.env # pour docker MinInt
    image: carto-rna
    build:
      context: ../
      args:
        - HTTP=${HTTP} # pour docker MinInt
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_API_BAN_URL=${VITE_API_BAN_URL}
        - VITE_API_ETABLISSEMENTS_PUBLICS_URL=${VITE_API_ETABLISSEMENTS_PUBLICS_URL}
      dockerfile: .docker/Dockerfile
    ports:
      - ${FRONT_PORT:-8000}:80
